language: dart
sudo: false
dart:
  - stable
  - dev
with_content_shell: true
cache:
  directories:
    - $HOME/.pub-cache
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script: ./tools/before_travis.sh
script: ./tools/travis.sh
