name: engine_2d
description: A 2d engine supporting multiple renderers.
version: 0.0.1
#author: Thomas Hourlier <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  meta: '>=1.0.0 <2.0.0'
#  angular2: '^2.0.0-beta.18'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- dart_to_js_script_rewriter